plugins {
    id 'java'
    id 'checkstyle'
    id 'pmd'
    id 'jacoco'
    id 'nebula.lint' version '20.6.2'
}

group 'no.unit.bibs'
version '1.0-SNAPSHOT'

java {
    sourceCompatibility = JavaVersion.VERSION_21 // source-code version and must be <= targetCompatibility
    targetCompatibility = JavaVersion.VERSION_21 // bytecode target version
}

repositories {
    mavenCentral()
    maven { url "https://jitpack.io" }
}

wrapper {
    distributionType = Wrapper.DistributionType.ALL
    gradleVersion = "8.14.3"
}


dependencies {

    implementation group: 'org.slf4j', name: 'slf4j-api', version: '2.0.17'
    implementation group: 'org.apache.logging.log4j', name: 'log4j-api', version: '2.25.2'
    implementation group: 'org.apache.logging.log4j', name: 'log4j-core', version: '2.25.2'

    implementation group: 'com.fasterxml.jackson.core', name: 'jackson-annotations', version: '2.19.1'
    implementation group: 'com.fasterxml.jackson.core', name: 'jackson-core', version: '2.19.1'
    implementation group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: '2.19.1'

    implementation group: 'com.amazonaws', name: 'aws-lambda-java-core', version: '1.3.0'
    implementation group: 'software.amazon.awssdk', name: 'dynamodb', version: '2.34.2'
    implementation group: 'software.amazon.awssdk', name: 's3', version: '2.31.78'
    implementation group: 'software.amazon.awssdk', name: 'aws-core', version: '2.34.2'
    implementation group: 'software.amazon.awssdk', name: 'http-client-spi', version: '2.34.2'
    implementation group: 'software.amazon.awssdk', name: 'regions', version: '2.34.2'
    implementation group: 'software.amazon.awssdk', name: 'sdk-core', version: '2.34.2'

    implementation group: 'org.apache.commons', name: 'commons-text', version: '1.14.0'
    implementation group: 'org.apache.commons', name: 'commons-lang3', version: '3.18.0'

    implementation group: 'com.github.bibsysdev', name: 'json', version: '2.3.18'
    implementation group: 'com.github.bibsysdev', name: 'core', version: '2.3.18'
    implementation group: 'com.github.bibsysdev', name: 'apigateway', version: '2.3.18'
    implementation group: 'com.github.bibsysdev', name: 'nvatestutils', version: '2.3.18'

    testImplementation group: 'org.mockito', name: 'mockito-core', version: '5.20.0'
    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.14.1'
    testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter', version: '5.14.1'

}

gradleLint {
    rules = ['all-dependency']
    reportFormat = 'html'
    reportOnlyFixableViolations = true
}

test {

    useJUnitPlatform()
    failFast = true
    finalizedBy jacocoTestReport
    testLogging {
        events "SKIPPED", "FAILED"
    }
    environment("COGNITO_AUTHORIZER_URLS", "https://test/jwks.json,https://test2/jwks.json")
}

pmd {
    toolVersion = '7.17.0'
    ruleSetConfig = rootProject.resources.text.fromFile('config/pmd/ruleset.xml')
    ruleSets = []
    ignoreFailures = false

}

checkstyle {
    toolVersion = '10.26.1'
    configFile = rootProject.resources.text.fromFile('config/checkstyle/checkstyle.xml').asFile()
    showViolations = true
}

tasks.withType(Checkstyle).configureEach {
    reports {
        html.required
        html.stylesheet = rootProject.resources.text.fromFile('config/checkstyle/checkstyle-simple.xsl')
    }
}

jacocoTestReport {
    reports {
        html.outputLocation.set(layout.buildDirectory.dir("reports/jacoco"))
    }
}

jacoco {
    toolVersion = "0.8.13"
}

check.dependsOn jacocoTestCoverageVerification
jacocoTestCoverageVerification.dependsOn(jacocoTestReport)

jacocoTestCoverageVerification {
    violationRules {
        rule {
            limit {
                counter = 'METHOD'
                value = 'COVEREDRATIO'
                minimum = 0.90
            }
        }

        rule {
            limit {
                counter = 'CLASS'
                value = 'COVEREDRATIO'
                minimum = 1.0
            }
        }
    }
}

