AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    Contents API and Handler

Parameters:
  CustomDomain:
    Type: AWS::SSM::Parameter::Value<String>
    Default: '/api/domainName'
    Description: (Optional) Custom domain name for the API endpoint
  CustomDomainBasePath:
    Type: String
    Default: 'contents'
    Description: (Optional) Base path mapping in CustomDomain
    AllowedPattern: "^[a-zA-Z0-9$\\-_.+!*'(),]*$"
    ConstraintDescription: "May contain only letters, numbers and one of $-_.+!*'(),"
  DynamoDBTableName:
    Type: String
    Default: 'contents'
    Description: DynamoDB table name
  BucketName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: '/contents/s3-storage-name'
    Description: Contents S3 bucket name

Conditions:
  HasDomainName: !Not [!Equals [!Ref CustomDomain, '']]
  HasCustomDomainBasePath: !Not [!Equals [!Ref CustomDomainBasePath, '']]

Globals:
  Function:
    Timeout: 20
  Api:
    Cors:
      AllowHeaders: '''Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'''
      AllowMethods: '''OPTIONS, POST, GET, PUT'''
      AllowOrigin: '''*'''
    EndpointConfiguration: REGIONAL

Resources:

  AccessDynamoDBRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: [lambda.amazonaws.com]
            Action: ['sts:AssumeRole']
      Policies:
        - PolicyName: writeLog
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*:*'
        - PolicyName: accessToDynamDB
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:*
                Resource: !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/*'
        - PolicyName: accessToS3Bucket
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                Resource:
                  - !Sub 'arn:aws:s3:::${BucketName}'
                  - !Sub 'arn:aws:s3:::${BucketName}/*'

  ContentsDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        -
          AttributeName: "isbn"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "isbn"
          KeyType: "HASH"
      TableName: !Ref DynamoDBTableName
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  DynamoDBTableNameContentsParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /contents/dynamoDBTableNameContents
      Type: String
      Value: !Ref DynamoDBTableName
      Description: Name of the contents table in DynamoDB
      AllowedPattern: "^[a-zA-Z]{1,10}$"

  DynamoDBStreamArnContentsParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /contents/dynamoDBStreamArnContents
      Type: String
      Value: !GetAtt ContentsDynamoDBTable.StreamArn
      Description: Arn to contents table DynamoDB stream

  ContentsApi:
    Type: AWS::Serverless::Api
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W64
            reason: "Skip access logging for artifacts bucket"
          - id: W68
            reason: "Skip encryption for artifacts bucket"
          - id: W69
            reason: "Skip bucket policy for artifacts bucket"
    Properties:
      Name: !Sub "${AWS::StackName}"
      StageName: v1
      EndpointConfiguration:
        Type: REGIONAL
      Auth:
        ResourcePolicy:
          CustomStatements:
            - Effect: Allow
              Principal: '*'
              Action: 'execute-api:Invoke'
              Resource: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*'
            - Effect: Allow
              Principal: '*'
              Action: 'execute-api:Invoke'
              Resource:
                - !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/PUT/'
                - !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/POST/'
              Condition:
                IpAddress:
                  'aws:SourceIp':
                    - 35.156.26.140
                    - 80.212.255.137
                    - 158.36.131.0/24
            - Effect: Allow
              Principal:
                - AWS: !Sub 'arn:aws:iam:${AWS::AccountId}:root'
              Action: 'execute-api:Invoke'
              Resource: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/POST/'

      DefinitionBody:
        openapi: 3.0.3
        info:
          title: Contents API
          version: '1.0'
        paths:
          /:
            get:
              description: "Search for contents by given isbn"
              consumes:
                - application/json
              produces:
                - application/json
              parameters:
                - in: query
                  name: isbn
                  description: "isbn to look for i contents."
                  required: false
                  schema:
                    type: string
              x-amazon-apigateway-integration:
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetContentsApiFunction.Arn}/invocations
                responses: {}
                httpMethod: POST
                type: AWS_PROXY
              responses:
                '200':
                  description: "OK"
                  content:
                    application/json:
                      schema:
                        $ref: '#/definitions/Contents'
                '404':
                  description: "Not Found"
                  content:
                    application/json:
                      schema:
                        $ref: '#/definitions/Contents'
                '500':
                  description: "Internal Server Error"
                  content:
                    application/json:
                      schema:
                        $ref: '#/definitions/Problem'
            post:
              description: "Adds contents"
              consumes:
                - application/json
              produces:
                - application/json
              parameters:
                - in: body
                  name: contents
                  description: "contents metadata"
                  required: true
                  schema:
                    type: string
              x-amazon-apigateway-integration:
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreateContentsApiFunction.Arn}/invocations
                responses: {}
                httpMethod: POST
                type: AWS_PROXY
              responses:
                '201':
                  description: "Created"
                  content:
                    application/json:
                      schema:
                        $ref: '#/definitions/Contents'
                '500':
                  description: "Internal Server Error"
                  content:
                    application/json:
                      schema:
                        $ref: '#/definitions/Problem'
            put:
              description: "Update or adds contents"
              consumes:
                - application/json
              produces:
                - application/json
              parameters:
                - in: body
                  name: contents
                  description: "contents metadata"
                  required: true
                  schema:
                    type: string
              x-amazon-apigateway-integration:
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UpdateContentsApiFunction.Arn}/invocations
                responses: { }
                httpMethod: POST
                type: AWS_PROXY
              responses:
                '200':
                  description: "OK"
                  content:
                    application/json:
                      schema:
                        $ref: '#/definitions/Contents'
                '201':
                  description: "Created"
                  content:
                    application/json:
                      schema:
                        $ref: '#/definitions/Contents'
                '500':
                  description: "Internal Server Error"
                  content:
                    application/json:
                      schema:
                        $ref: '#/definitions/Problem'
        definitions:
          Contents:
            type: object
          Problem:
            type: object
            description: Internal Server Error is logged
            properties:
              title:
                type: string
              status:
                type: integer
              detail:
                type: string
              requestId:
                type: string

  GetContentsApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Tracing: Active
      Handler: no.unit.bibs.contents.GetContentsApiHandler::handleRequest
      Runtime: java11
      MemorySize: 1024
      Role: !GetAtt AccessDynamoDBRole.Arn
      Environment:
        Variables:
          ALLOWED_ORIGIN: '*'
          TABLE_NAME: !Ref DynamoDBTableName
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId: !Ref ContentsApi

  CreateContentsApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Tracing: Active
      Handler: no.unit.bibs.contents.CreateContentsApiHandler::handleRequest
      Runtime: java11
      MemorySize: 1024
      Role: !GetAtt AccessDynamoDBRole.Arn
      Environment:
        Variables:
          ALLOWED_ORIGIN: '*'
          TABLE_NAME: !Ref DynamoDBTableName
          BUCKET_NAME: !Ref BucketName
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: /
            Method: post
            RestApiId: !Ref ContentsApi

  UpdateContentsApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Tracing: Active
      Handler: no.unit.bibs.contents.UpdateContentsApiHandler::handleRequest
      Runtime: java11
      MemorySize: 1024
      Role: !GetAtt AccessDynamoDBRole.Arn
      Environment:
        Variables:
          ALLOWED_ORIGIN: '*'
          TABLE_NAME: !Ref DynamoDBTableName
          BUCKET_NAME: !Ref BucketName
      Events:
        PutEvent:
          Type: Api
          Properties:
            Path: /
            Method: put
            RestApiId: !Ref ContentsApi

  UpdateContentsApiFunctionAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "UpdateContentsApiFunctionAlarm-${AWS::StackName}"
      AlarmDescription: 'Error in function.'
      Namespace: AWS/Lambda
      Dimensions:
        - Name: FunctionName
          Value: !Ref UpdateContentsApiFunction
      MetricName: Errors
      Statistic: Sum
      Period: 600 #10 minutes
      EvaluationPeriods: 1
      Threshold: 0
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref UpdateContentsApiFunctionAlarmNotification

  UpdateContentsApiFunctionAlarmNotification:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "UpdateContentsApiFunctionAlarmNotification-${AWS::StackName}"

  GetContentsApiFunctionAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "GetContentsApiFunctionAlarm-${AWS::StackName}"
      AlarmDescription: 'Error in function.'
      Namespace: AWS/Lambda
      Dimensions:
        - Name: FunctionName
          Value: !Ref GetContentsApiFunction
      MetricName: Errors
      Statistic: Sum
      Period: 600 #10 minutes
      EvaluationPeriods: 1
      Threshold: 0
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref GetContentsApiFunctionAlarmNotification

  GetContentsApiFunctionAlarmNotification:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "GetContentsApiFunctionAlarmNotification-${AWS::StackName}"

  GetContentsApiFunctionUsageAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "GetContentsApiFunctionUsageAlarm-${AWS::StackName}"
      AlarmDescription: 'Invocations of function exceeding threshold.'
      Namespace: AWS/Lambda
      Dimensions:
        - Name: FunctionName
          Value: !Ref GetContentsApiFunction
      MetricName: Invocations
      Statistic: Sum
      Period: 300 #5 minutes
      EvaluationPeriods: 1
      Threshold: 500
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref GetContentsApiFunctionUsageAlarmNotification

  GetContentsApiFunctionUsageAlarmNotification:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "GetContentsApiFunctionUsageAlarmNotification-${AWS::StackName}"

  ContentsBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Condition: HasDomainName
    Properties:
      BasePath: !If
        - HasCustomDomainBasePath
        - !Ref CustomDomainBasePath
        - !Ref 'AWS::NoValue'
      DomainName: !Ref CustomDomain
      RestApiId: !Ref ContentsApi
      Stage: !Ref ContentsApi.Stage

Outputs:
  ApiEndpoint:
    Description: "Endpoint base URL for the API"
    Value: !If
      - HasDomainName
      - !Sub "https://${CustomDomain}/${CustomDomainBasePath}"
      - !Sub "https://${ContentsApi}.execute-api.${AWS::Region}.amazonaws.com/${ContentsApi.Stage}/"
